name: Code Quality

on:
  push:
    branches:
      - main
      - feat/add-financial-service
  pull_request:
    branches:
      - main

jobs:
  format-check:
    name: Code Formatting Check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Restore from cache and setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Check code formatting
        run: |
          cmake --preset ninja-multi-vcpkg
          cmake --workflow --preset check-format
