name: Tests

on:
  push:
    branches:
      - main
      - feat/add-financial-service
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit Tests on ${{ matrix.os }} for ${{ matrix.config }} config
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [debug, release]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      - name: Run tests (full workflow)
        run: cmake --workflow --preset test-${{ matrix.config }}
